# Generated by Django 4.2.24 on 2025-09-30 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('owner', 'Owner'), ('admin', 'Admin')], default='user', max_length=10),
        ),
    ]
