# Generated by Django 4.2.24 on 2025-12-07 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_phone_user_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='discord',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='next_request_permission',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
