# Generated by Django 4.2.24 on 2025-10-06 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0007_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="subtitle",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
