# Generated by Django 4.2.24 on 2025-10-06 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0009_product_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="Slider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("picture", models.ImageField(upload_to="sliders/")),
                ("link", models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
