# Generated by Django 4.2.24 on 2025-10-07 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0010_slider"),
    ]

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[("left", "Left"), ("right", "Right")],
                        max_length=5,
                        unique=True,
                    ),
                ),
                ("image", models.ImageField(upload_to="banners/")),
                ("link", models.URLField(blank=True, null=True)),
            ],
        ),
    ]
