# Generated by Django 4.2.24 on 2025-10-07 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0011_banner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banner",
            name="position",
            field=models.CharField(
                choices=[("left", "Left"), ("right", "Right")], max_length=5
            ),
        ),
    ]
