# Generated by Django 4.2.24 on 2025-10-12 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0012_alter_banner_position"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slider",
            name="link",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
