# Generated by Django 4.2.24 on 2025-10-14 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0014_alter_banner_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.BigIntegerField(),
        ),
    ]
