# Generated by Django 4.2.24 on 2025-11-01 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_menucategory_section_menuitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Section',
            new_name='MenuSection',
        ),
    ]
