# Generated by Django 4.2.24 on 2025-11-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_rename_section_menusection'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmazingSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.PositiveIntegerField(help_text='Duration in seconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('products', models.ManyToManyField(related_name='amazing_sliders', to='shop.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
