# Generated by Django 4.2.24 on 2025-11-26 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_amazingslider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazingslider',
            name='duration',
            field=models.PositiveIntegerField(),
        ),
    ]
