# Generated by Django 4.2.24 on 2025-11-27 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='card_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='card_pan',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='error_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='error_message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='fee',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='fee_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='ref_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
