# Generated by Django 4.2.24 on 2025-11-27 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_checkout_card_hash_checkout_card_pan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='items',
            field=models.JSONField(default=list, null=True),
        ),
    ]
