# Generated by Django 4.2.24 on 2025-11-27 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_checkout_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='items',
            field=models.JSONField(default=list),
        ),
    ]
