# Generated by Django 4.2.24 on 2026-01-02 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_discount_discountusage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountusage',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
