# Generated by Django 4.2.24 on 2026-01-02 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_discountusage_is_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discountusage',
            name='is_used',
        ),
        migrations.AddField(
            model_name='discount',
            name='discount_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='discount',
            name='offer_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
