# Generated by Django 4.2.24 on 2026-01-02 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_remove_discountusage_is_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='offer_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
