# Generated by Django 4.2.24 on 2026-01-07 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_checkout_offer_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='menucategory',
            name='link',
            field=models.CharField(default='/products', max_length=255),
        ),
    ]
