# Generated by Django 4.2.24 on 2026-02-14 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_menucategory_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
